dashboard:
  restart: "always"
  build: ./dashboard
  volumes:
    - /usr/src/app/static
  env_file: settings/dashboard.env
  container_name: titdev_dashboard
  net: "titdev_network"

nginx:
  restart: "always"
  build: ./nginx
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - dashboard
  container_name: titdev_nginx
  net: "titdev_network"

dbdata:
  restart: "no"
  image: mongo:latest
  volumes:
    - /data/db
    - /data/murmur
  command: echo "Data Container for Primary and Murmur Database"
  container_name: titdev_dbdata
  net: "none"

database:
  restart: "always"
  build: ./database
  volumes_from:
    - dbdata
  ports:
    - "27017:27017"
  command: --auth
  container_name: titdev_database
  net: "titdev_network"

murmur:
  restart: "always"
  build: ./murmur
  volumes_from:
  - dbdata
  ports:
    - "64738:64738"
    - "64738:64738/udp"
  container_name: titdev_murmur
  env_file: settings/dashboard.env
  net: "titdev_network"

mumo:
  restart: "always"
  build: ./mumo
  container_name: titdev_mumo
  net: "titdev_network"