dashboard:
  restart: "always"
  build: ./dashboard
  volumes:
    - /usr/src/app/static
  env_file: settings/dashboard.env
  container_name: titdev-dashboard
  net: "titdev-network"

nginx:
  restart: "always"
  build: ./nginx
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - dashboard
  container_name: titdev-nginx
  net: "titdev-network"

dbdata:
  restart: "no"
  image: mongo:latest
  volumes:
    - /data/db
    - /data/murmur
  command: echo "Data Container for Primary and Murmur Database"
  container_name: titdev-dbdata
  net: "none"

database:
  restart: "always"
  build: ./database
  volumes_from:
    - dbdata
  ports:
    - "27017:27017"
  command: --auth
  container_name: titdev-database
  net: "titdev-network"

murmur:
  restart: "always"
  build: ./murmur
  volumes_from:
  - dbdata
  ports:
    - "64738:64738"
    - "64738:64738/udp"
  container_name: titdev-murmur
  env_file: settings/dashboard.env
  net: "titdev-network"

mumo:
  restart: "always"
  build: ./mumo
  container_name: titdev-mumo
  net: "titdev-network"

redis:
  restart: "always"
  image: redis:latest
  container_name: titdev-redis
  net: "titdev-network"

discord:
  restart: "always"
  build: ./discord
  container_name: titdev-discord
  env_file: settings/dashboard.env
  net: "titdev-network"
