dashboard:
  restart: "always"
  build: ./dashboard
  links:
    - database:database
  volumes:
    - /usr/src/app/static
  env_file: settings/dashboard.env
  container_name: titdev_dashboard

nginx:
  restart: "always"
  build: ./nginx
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - dashboard
  links:
    - dashboard:dashboard
  external_links:
    - discourse
  container_name: titdev_nginx

dbdata:
  restart: "no"
  image: mongo:latest
  volumes:
    - /data/db
  command: echo "Data Container for Primary Database"
  container_name: titdev_dbdata

database:
  restart: "always"
  build: ./database
  volumes_from:
    - dbdata
  ports:
    - "27017:27017"
  container_name: titdev_database

murmur:
  restart: "always"
  build: ./murmur
  volumes:
  - /data/murmur
  ports:
    - "64738:64738"
  container_name: titdev_murmur